ServerEvents.recipes((machine) => {
    //液体提取器
    machine.recipes.ars_nouveau.enchanting_apparatus([
        'mekanism:ultimate_fluid_tank','mekanism:ultimate_mechanical_pipe',
        'mekanism:ultimate_mechanical_pipe','mekanism:ultimate_fluid_tank',
        'mekanism:ultimate_mechanical_pipe','mekanism:ultimate_mechanical_pipe',
        'minecraft:piston','mekanism:ultimate_mechanical_pipe',
        'mekanism:ultimate_mechanical_pipe','mekanism:ultimate_fluid_tank',
        'mekanism:ultimate_mechanical_pipe','mekanism:ultimate_mechanical_pipe',
    ],
    'industrialforegoing:machine_frame_pity',
    'industrialforegoing:fluid_extractor',
    10000
    ).id('kubejs:fluid_extractor')
    //胶乳处理单元
    machine.recipes.ars_nouveau.enchanting_apparatus([
        'mekanism:ultimate_fluid_tank','mekanism:ultimate_mechanical_pipe',
        'mekanism:ultimate_mechanical_pipe','mekanism:ultimate_control_circuit',
        'mekanism:ultimate_mechanical_pipe','mekanism:ultimate_mechanical_pipe',
        'create:blaze_burner','mekanism:ultimate_mechanical_pipe',
        'mekanism:ultimate_mechanical_pipe','mekanism:ultimate_control_circuit',
        'mekanism:ultimate_mechanical_pipe','mekanism:ultimate_mechanical_pipe',
    ],
    'industrialforegoing:machine_frame_pity',
    'industrialforegoing:latex_processing_unit',
    10000
    ).id('kubejs:latex_processing_unit')
    //化学溶解室
    machine.recipes.ars_nouveau.enchanting_apparatus([
        'mekanism:ultimate_fluid_tank','industrialforegoing:plastic','mekanism:ultimate_logistical_transporter',
        'mekanism:ultimate_control_circuit','mekanism:ultimate_logistical_transporter','industrialforegoing:plastic',
        'create:whisk','industrialforegoing:plastic','mekanism:ultimate_logistical_transporter',
        'mekanism:ultimate_control_circuit','mekanism:ultimate_logistical_transporter','industrialforegoing:plastic',
    ],
    'industrialforegoing:machine_frame_pity',
    'industrialforegoing:dissolution_chamber',
    10000
    ).id('kubejs:dissolution_chamber')

    //镭射钻
    machine.recipes.industrialforegoing.dissolution_chamber([
        'minecraft:netherite_pickaxe','minecraft:netherite_axe','minecraft:netherite_shovel',
        'industrialforegoing:machine_frame_simple','industrialforegoing:machine_frame_simple','ae2:singularity',
        'industrialforegoing:fluid_laser_base','ae2:singularity',
    ],
    'mekanism:fluid_purple',
    'industrialforegoing:laser_drill',
    100
    ).id('kubejs:laser_drill')

    //流体镭射钻基座
    machine.recipes.industrialforegoing.dissolution_chamber([
        'industrialforegoing:machine_frame_simple','industrialforegoing:machine_frame_simple','industrialforegoing:machine_frame_simple',
        'ae2:singularity','ae2:singularity',
        'industrialforegoing:machine_frame_simple','industrialforegoing:machine_frame_simple','industrialforegoing:machine_frame_simple',
    ],
    'mekanism:fluid_white',
    'industrialforegoing:fluid_laser_base',
    100
    ).id('kubejs:fluid_laser_base')

    //矿物镭射钻基座
    machine.recipes.industrialforegoing.dissolution_chamber([
        'industrialforegoing:machine_frame_advanced','minecraft:netherite_pickaxe','industrialforegoing:machine_frame_advanced',
        'ae2:singularity','ae2:singularity',
        'industrialforegoing:machine_frame_advanced','minecraft:netherite_pickaxe','industrialforegoing:machine_frame_advanced',
    ],
    Fluid.of('industrialforegoing:pink_slime',1000),
    'industrialforegoing:ore_laser_base',
    100
    ).id('kubejs:ore_laser_base')

    //冷凝室
    machine.recipes.industrialforegoing.dissolution_chamber([
        'minecraft:soul_sand','minecraft:soul_sand','minecraft:soul_sand',
        'thermal:enderium_ingot','thermal:enderium_ingot',
        'thermal:signalum_gear','industrialforegoing:machine_frame_advanced','thermal:signalum_gear',
    ],
    Fluid.of('thermal:ender',1000),
    'industrialforegoing:stasis_chamber',
    1000)
})
